apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name
  - select:
      kind: Secret
    fieldPaths:
    - metadata.namespace
  - select:
      kind: ConfigMap
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Role
    fieldPaths:
    - metadata.namespace
  - select:
      kind: RoleBinding
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.namespace
  - select:
      kind: ServiceAccount
    fieldPaths:
    - metadata.namespace
  - select:
      kind: RoleBinding
    fieldPaths:
    - subjects.0.namespace
