apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: amf-config
  namespace: amf-example
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: AMFDeployment
    metadata:
      name: amf-config
      namespace: oaicp
    spec:
      logLevel: info
      plmn:
        mcc: '001'
        mnc: '01'
        tac: '0x0001'
      nssai:
        - sst: 1
          sd: 'FFFFFF'
      image: 'docker.io/oaisoftwarealliance/oai-amf:develop'
      fqdn:
        smf: 'smf-regional'
        ausf: 'ausf-regional'
        nrf: 'nrf-regional'
        udm: 'udm-regional'