apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /set-annotation
  name: set-configuration
  annotations:
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|set-configuration
source: |-
  for resource in ctx.resource_list["items"]:
    if resource.get("kind") == "AMFDeployment" and resource.get("spec") != None:
      if resource["spec"].get("configRefs") != None :
        resource["spec"]["configRefs"].append({"name": "amf-config",
                                               "namespace": "oaicp", 
                                               "apiVersion": "ref.nephio.org/v1alpha1", 
                                               "kind": "Config"
                                               })
      else:
        resource['spec'].update({"configRefs": {"name": "amf-config",
                                               "namespace": "oaicp", 
                                               "apiVersion": "ref.nephio.org/v1alpha1", 
                                               "kind": "Config"
                                               }})
    elif resource.get("kind") == "AMFDeployment":
      resource.update({"spec": {"configRefs": {"name": "amf-config",
                                               "namespace": "oaicp", 
                                               "apiVersion": "ref.nephio.org/v1alpha1", 
                                               "kind": "Config"
                                               }}})