apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: smf-config
  namespace: smf-example
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: SMFDeployment
    metadata:
      name: smf-config
      namespace: oaicp
    spec:
      logLevel: info
      image: 'docker.io/oaisoftwarealliance/oai-smf:develop'
      nssai:
        - sst: 1
          sd: 'FFFFFF'
      ueSettings:
        primary: 8.8.8.8
        secondary: 4.4.4.4
        mtu: 1500
      fqdn:
        nrf: 'nrf-regional'
        udm: 'udm-regional'
        amf: 'amf-regional'