apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: smf-example
  namespace: smf-example
spec:
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig