apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: regional-oai-ausf
spec:
  upstream:
    repo: oai-packages
    package: oai-ausf
    revision: onesummit
  downstream:
    repo: regional
    package: oai-ausf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: regional
