apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-database
spec:
  upstream:
    repo: oai-packages
    package: database
    revision: onesummit
  downstream:
    repo: core
    package: database
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core
