apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariant
metadata:
  name: regional-oai-nrf
spec:
  upstream:
    repo: oai-packages
    package: oai-nrf
    revision: onesummit
  downstream:
    repo: regional
    package: oai-nrf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: regional
