apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oainrue
spec:
  upstream:
    repo: oai-packages
    package: oai-nr-ue
    revision: r2
  downstream:
    repo: edge
    package: oai-nr-ue
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
