apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-cp-operators
spec:
  upstream:
    repo: oai-packages
    package: oai-cp-operators
    revision: onesummit
  downstream:
    repo: regional
    package: oai-cp-operators
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: regional