apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: oai-cp-operators
spec:
  upstream:
    repo: oai-packages
    package: oai-cp-operators
    revision: develop
  targets:
  - objectSelector:
      apiVersion: infra.nephio.org/v1alpha1
      kind: WorkloadCluster
    template:
      annotations:
        approval.nephio.org/policy: initial
