apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariantSet
metadata:
  name: regional-oai-udm
spec:
  upstream:
    repo: oai-packages
    package: oai-udm
    revision: onesummit
  downstream:
    repo: regional
    package: oai-udm
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: regional
