apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: core-oai-udr
spec:
  upstream:
    repo: oai-core-packages
    package: oai-udr
    revision: r3
  targets:
  - objectSelector:
      apiVersion: infra.nephio.org/v1alpha1
      kind: WorkloadCluster
      matchLabels:
        nephio.org/site-type: core
    template:
      downstream:
        package: oai-udr
      annotations:
        approval.nephio.org/policy: initial
      injectors:
      - nameExpr: target.name
