apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-upf
spec:
  upstream:
    repo: oai-core-packages
    package: oai-upf-edge
    revision: r3
  downstream:
    repo: edge
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge
