apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-upf-edge
spec:
  upstream:
    repo: oai-packages
    package: oai-upf-edge
    revision: r2
  downstream:
    repo: edge01
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge01
