apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge01-oai-upf
spec:
  upstream:
    repo: oai-packages
    package: oai-upf-edge01
    revision: develop
  downstream:
    repo: edge01
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge01
