apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge02-oai-upf
spec:
  upstream:
    repo: oai-packages
    package: oai-upf-edge02
    revision: develop
  downstream:
    repo: edge02
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge02
