apiVersion: v1
kind: ServiceAccount
metadata:
  name: oai-nr-ue-sa-2
  namespace: oai5g-ran
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-nr-ue-configmap-2
  namespace: oai5g-ran
data:
  dnn: "oai"
  fullImsi: "001010000000101"
  fullKey: "fec86ba6eb707ed08905757b1bb44b8f"
  nssaiSd: "16777215"
  nssaiSst: "1"
  opc: "C42449363BBAD02B66D16BC975D77CC1"
  rfSimulator: "oai-gnb"
  timeZone: "Europe/Paris"
  useAdditionalOptions: "--sa -E --rfsim -r 106 --numerology 1 -C 3319680000 --nokrnmod --log_config.global_log_options level,nocolor,time"

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: oai-nr-ue-configmap-2
# data:
#   nrue.conf: |
#       uicc0 = {
#       imsi = "001010000000100";
#       key = "fec86ba6eb707ed08905757b1bb44b8f";
#       opc= "C42449363BBAD02B66D16BC975D77CC1";
#       dnn= "oai";
#       nssai_sst="1";
#       nssai_sd="16777215";
#       }
---
# Source: oai-nr-ue/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nr-ue-2
  namespace: oai5g-ran
  labels:
    app.kubernetes.io/name: oai-nr-ue-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-nr-ue-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-nr-ue-2
      annotations:
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nr-ue
        image: "docker.io/oaisoftwarealliance/oai-nr-ue:2023.w19"
        securityContext:
          privileged: true
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: timeZone
        - name: RFSIMULATOR
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: rfSimulator
        - name: FULL_IMSI
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: fullImsi
        - name: FULL_KEY
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: fullKey
        - name: OPC
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: opc
        - name: DNN
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: dnn
        - name: NSSAI_SST
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: nssaiSst
        - name: NSSAI_SD
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: nssaiSd
        - name: USE_ADDITIONAL_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: oai-nr-ue-configmap-2
              key: useAdditionalOptions
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: oai-nr-ue-sa-2
      terminationGracePeriodSeconds: 5
